const resList = [
    {
      info: {
        id: "723825",
        name: "Pizza Hut",
        cloudinaryImageId: "b78fb4af57487179b0043cf69fadf8a8",
        locality: "Tiruvalam Rd",
        areaName: "Selvam Nagar",
        costForTwo: "₹350 for two",
        cuisines: ["Pizzas"],
        avgRating: 4.2,
        parentId: "721",
        avgRatingString: "4.2",
        totalRatingsString: "500+",
        sla: {
          deliveryTime: 25,
          lastMileTravel: 2,
          serviceability: "SERVICEABLE",
          slaString: "20-25 mins",
          lastMileTravelString: "2.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/pizza-hut-tiruvalam-rd-selvam-nagar-vellore-723825",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "777436",
        name: "Thambi Biryani Kadai",
        cloudinaryImageId: "b14cd9fc40129fcfb97aa7e621719d07",
        locality: "Chitoor Vellore Road",
        areaName: "VIT Katpadi",
        costForTwo: "₹250 for two",
        cuisines: ["Indian", "Chinese", "Seafood", "Arabian", "Biryani"],
        avgRating: 4.3,
        parentId: "257067",
        avgRatingString: "4.3",
        totalRatingsString: "500+",
        sla: {
          deliveryTime: 18,
          lastMileTravel: 2.4,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "2.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 15:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        isNewlyOnboarded: true,
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/thambi-biryani-kadai-chitoor-road-vit-katpadi-vellore-777436",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "111016",
        name: "Hotel S.B.R",
        cloudinaryImageId: "vwjkwx9yt6tnbat0us5m",
        locality: "Bharathi nagar",
        areaName: "Katpadi",
        costForTwo: "₹350 for two",
        cuisines: [
          "Biryani",
          "Chinese",
          "South Indian",
          "Tandoor",
          "North Indian",
        ],
        avgRating: 4.4,
        parentId: "17508",
        avgRatingString: "4.4",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 17,
          lastMileTravel: 2.4,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "2.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 15:00:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
              description: "OnlyOnSwiggy",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "OnlyOnSwiggy",
                    imageId:
                      "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹80",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/hotel-s-b-r-bharathi-nagar-katpadi-vellore-111016",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "72849",
        name: "Domino's Pizza",
        cloudinaryImageId: "092e58460657922e098a8afd5db838fe",
        locality: "Cuddalore Chittoor Road",
        areaName: "Katpadi",
        costForTwo: "₹400 for two",
        cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
        avgRating: 4.5,
        parentId: "2456",
        avgRatingString: "4.5",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 30,
          serviceability: "SERVICEABLE",
          slaString: "30 mins",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-07 02:59:00",
          opened: true,
        },
        badges: {
          textExtendedBadges: [
            {
              iconId: "Ratnesh_Badges/free%20del%20icon.png",
              shortDescription: "Free Delivery",
              fontColor: "#7E808C",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {
              badgeObject: [
                {
                  attributes: {
                    description: "",
                    fontColor: "#7E808C",
                    iconId: "Ratnesh_Badges/free%20del%20icon.png",
                    shortDescription: "Free Delivery",
                  },
                },
              ],
            },
          },
        },
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹50",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/dominos-pizza-cuddalore-chittoor-road-katpadi-vellore-72849",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "489350",
        name: "The Vellore Kitchen",
        cloudinaryImageId: "f4pobi3sivggxqc1zigt",
        locality: "Suthanthira Ponvizha Nagar",
        areaName: "Silk Mill Bus Stop",
        costForTwo: "₹400 for two",
        cuisines: [
          "Biryani",
          "South Indian",
          "Chinese",
          "Kebabs",
          "Desserts",
          "Juices",
        ],
        avgRating: 4.4,
        parentId: "16937",
        avgRatingString: "4.4",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 23,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "20-25 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 22:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/the-vellore-kitchen-suthanthira-ponvizha-nagar-silk-mill-bus-stop-vellore-489350",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "71994",
        name: "Limra Garden Restaurant",
        cloudinaryImageId: "akpej3vji3bvpy5i9omc",
        locality: "Kangeyanallore Road",
        areaName: "Opposite VIT",
        costForTwo: "₹300 for two",
        cuisines: [
          "Chinese",
          "North Indian",
          "South Indian",
          "Pastas",
          "Burgers",
        ],
        avgRating: 4.4,
        parentId: "11749",
        avgRatingString: "4.4",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 20,
          lastMileTravel: 1.6,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "1.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 21:15:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
              description: "OnlyOnSwiggy",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "OnlyOnSwiggy",
                    imageId:
                      "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "10% OFF",
          subHeader: "UPTO ₹40",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/limra-garden-restaurant-kangeyanallore-road-opposite-vit-vellore-71994",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "71474",
        name: "Andhra Spice Multicuisine Restaurant",
        cloudinaryImageId: "l2dgumhwcxe7qmmpsvxi",
        locality: "Kangayanallur Road",
        areaName: "VIT Katpadi",
        costForTwo: "₹350 for two",
        cuisines: ["Biryani", "North Indian", "Andhra", "Fast Food"],
        avgRating: 4.3,
        parentId: "17695",
        avgRatingString: "4.3",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 16,
          lastMileTravel: 1.5,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "1.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/andhra-spice-multicuisine-restaurant-kangayanallur-road-vit-katpadi-vellore-71474",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "84080",
        name: "Fortune Deli by Fortune Park Vellore",
        cloudinaryImageId: "dh0dfo4xbjndu5ikr0kn",
        locality: "Suthanthira Ponvizha Nagar",
        areaName: "Gandhi Nagar",
        costForTwo: "₹250 for two",
        cuisines: ["Biryani", "Indian", "Continental", "Healthy Food"],
        avgRating: 4.2,
        parentId: "83202",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 27,
          lastMileTravel: 2.5,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "2.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 22:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/fortune-deli-by-fortune-park-vellore-suthanthira-ponvizha-nagar-gandhi-nagar-vellore-84080",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "84073",
        name: "Hundreds Heritage",
        cloudinaryImageId: "jioackq0asahaj69wpfe",
        locality: "Gandhinagar",
        areaName: "Gandhi Nagar",
        costForTwo: "₹600 for two",
        cuisines: [
          "Biryani",
          "Tandoor",
          "Chinese",
          "Pastas",
          "Pizzas",
          "Desserts",
          "Ice Cream",
          "Beverages",
        ],
        avgRating: 4.4,
        parentId: "17610",
        avgRatingString: "4.4",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 26,
          lastMileTravel: 2.4,
          serviceability: "SERVICEABLE",
          slaString: "25-30 mins",
          lastMileTravelString: "2.4 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 15:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/hundreds-heritage-gandhinagar-gandhi-nagar-vellore-84073",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "72934",
        name: "Alakar Restaurant Veg",
        cloudinaryImageId: "ti29qttelzyr9x3ihxyr",
        locality: "Chittoor Main Road",
        areaName: "Katpadi",
        costForTwo: "₹300 for two",
        cuisines: [
          "Biryani",
          "South Indian",
          "Chinese",
          "North Indian",
          "Juices",
          "Beverages",
        ],
        avgRating: 4.3,
        veg: true,
        parentId: "17668",
        avgRatingString: "4.3",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 20,
          lastMileTravel: 2.6,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "2.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 23:57:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹199",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/alakar-restaurant-veg-chittoor-main-road-katpadi-vellore-72934",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "163648",
        name: "B M S Biriyani",
        cloudinaryImageId: "zkfkygqqww37go7lca3u",
        locality: "Katpadi Road",
        areaName: "Silk Mill",
        costForTwo: "₹250 for two",
        cuisines: ["Biryani", "Chinese", "South Indian"],
        avgRating: 4.2,
        parentId: "17317",
        avgRatingString: "4.2",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 17,
          lastMileTravel: 3,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "3.0 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/b-m-s-biriyani-katpadi-road-silk-mill-vellore-163648",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "404404",
        name: "Grameen Kulfi",
        cloudinaryImageId: "wgq1vspolmxxikdwf6qy",
        locality: "Kaghaiyanal Road",
        areaName: "Vellore",
        costForTwo: "₹120 for two",
        cuisines: ["Ice Cream", "Desserts"],
        avgRating: 4.7,
        veg: true,
        parentId: "12175",
        avgRatingString: "4.7",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 16,
          lastMileTravel: 1.6,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "1.6 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 23:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "EVERY ITEM",
          subHeader: "@ ₹99",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/grameen-kulfi-kaghaiyanal-road-vellore-vellore-404404",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "663243",
        name: "Zaitoon",
        cloudinaryImageId: "3dd95cf5d718da0f33ca7c161d3b1318",
        locality: "Thiruvalam road",
        areaName: "VIT Katpadi",
        costForTwo: "₹800 for two",
        cuisines: [
          "Arabian",
          "Biryani",
          "Chinese",
          "Indian",
          "Kebabs",
          "Mughlai",
          "Juices",
        ],
        avgRating: 4.4,
        parentId: "4555",
        avgRatingString: "4.4",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 24,
          lastMileTravel: 1.7,
          serviceability: "SERVICEABLE",
          slaString: "20-25 mins",
          lastMileTravelString: "1.7 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 23:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        aggregatedDiscountInfoV2: {},
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/zaitoon-thiruvalam-road-vit-katpadi-vellore-663243",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "71477",
        name: "The Chocolate Room",
        cloudinaryImageId: "upb5cbq2ozuwlkvhswaj",
        locality: "Chennai Salai",
        areaName: "Opp to VIT Main Gate",
        costForTwo: "₹400 for two",
        cuisines: ["Bakery", "Pastas", "Pizzas", "Beverages", "Italian"],
        avgRating: 3.9,
        veg: true,
        parentId: "1002",
        avgRatingString: "3.9",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 20,
          lastMileTravel: 1.5,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "1.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 22:15:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1695133679/badges/Pure_Veg111.png",
              description: "pureveg",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "pureveg",
                    imageId: "v1695133679/badges/Pure_Veg111.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "40% OFF",
          subHeader: "UPTO ₹80",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/the-chocolate-room-chennai-salai-opp-to-vit-main-gate-vellore-71477",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "71475",
        name: "Apna Dhaba",
        cloudinaryImageId: "o4pc2ee1mlfizartuy5l",
        locality: "Vaibhav Nagar",
        areaName: "VIT-Katpadi",
        costForTwo: "₹350 for two",
        cuisines: ["Biryani", "North Indian", "Chinese"],
        avgRating: 4.2,
        parentId: "2958",
        avgRatingString: "4.2",
        totalRatingsString: "5K+",
        sla: {
          deliveryTime: 23,
          lastMileTravel: 1.5,
          serviceability: "SERVICEABLE",
          slaString: "20-25 mins",
          lastMileTravelString: "1.5 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-07 00:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "30% OFF",
          subHeader: "UPTO ₹75",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/apna-dhaba-vaibhav-nagar-vit-katpadi-vellore-71475",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "713457",
        name: "Hotel Aryaas",
        cloudinaryImageId: "f34657e4f398eec0e714971b58f8be69",
        locality: "Gandhi Nagar",
        areaName: "Gandhinagar",
        costForTwo: "₹250 for two",
        cuisines: [
          "South Indian",
          "North Indian",
          "Snacks",
          "Beverages",
          "Juices",
        ],
        avgRating: 4.5,
        veg: true,
        parentId: "16963",
        avgRatingString: "4.5",
        totalRatingsString: "100+",
        sla: {
          deliveryTime: 17,
          lastMileTravel: 2.1,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "2.1 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 22:00:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "20% OFF",
          subHeader: "UPTO ₹100",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/hotel-aryaas-gandhi-nagar-gandhinagar-vellore-713457",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "71993",
        name: "Abhiruchi Restaurant",
        cloudinaryImageId: "mmwhwne45z6iyjkjvk77",
        locality: "Auxillium College Road",
        areaName: "Gandhinagar",
        costForTwo: "₹350 for two",
        cuisines: ["Biryani", "South Indian", "Chinese", "North Indian"],
        avgRating: 4.4,
        parentId: "5664",
        avgRatingString: "4.4",
        totalRatingsString: "10K+",
        sla: {
          deliveryTime: 18,
          lastMileTravel: 1.9,
          serviceability: "SERVICEABLE",
          slaString: "15-20 mins",
          lastMileTravelString: "1.9 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 15:30:00",
          opened: true,
        },
        badges: {
          imageBadges: [
            {
              imageId: "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
              description: "OnlyOnSwiggy",
            },
          ],
        },
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {
              badgeObject: [
                {
                  attributes: {
                    description: "OnlyOnSwiggy",
                    imageId:
                      "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png",
                  },
                },
              ],
            },
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "₹125 OFF",
          subHeader: "ABOVE ₹249",
          discountTag: "FLAT DEAL",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/abhiruchi-restaurant-auxillium-college-road-gandhinagar-vellore-71993",
        type: "WEBLINK",
      },
    },
    {
      info: {
        id: "428315",
        name: "Saffron Restaurant",
        cloudinaryImageId: "qwxk6bjca5p7q0y4yuu6",
        locality: "Katpadi",
        areaName: "VIT-Katpadi",
        costForTwo: "₹300 for two",
        cuisines: [
          "Biryani",
          "North Indian",
          "Tandoor",
          "South Indian",
          "Ice Cream",
          "Street Food",
        ],
        avgRating: 4.1,
        parentId: "18723",
        avgRatingString: "4.1",
        totalRatingsString: "1K+",
        sla: {
          deliveryTime: 21,
          lastMileTravel: 2.2,
          serviceability: "SERVICEABLE",
          slaString: "20-25 mins",
          lastMileTravelString: "2.2 km",
          iconType: "ICON_TYPE_EMPTY",
        },
        availability: {
          nextCloseTime: "2024-03-06 15:30:00",
          opened: true,
        },
        badges: {},
        isOpen: true,
        type: "F",
        badgesV2: {
          entityBadges: {
            imageBased: {},
            textBased: {},
            textExtendedBadges: {},
          },
        },
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
        },
        differentiatedUi: {
          displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
          differentiatedUiMediaDetails: {
            mediaType: "ADS_MEDIA_ENUM_IMAGE",
            lottie: {},
            video: {},
          },
        },
        reviewsSummary: {},
        displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
        restaurantOfferPresentationInfo: {},
      },
      analytics: {},
      cta: {
        link: "https://www.swiggy.com/restaurants/saffron-restaurant-katpadi-vit-katpadi-vellore-428315",
        type: "WEBLINK",
      },
    },
  ];
export default resList;